global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'url-shortener'
    static_configs:
      - targets: 
          - 'url-shortener-dev-app1:3000'
          - 'url-shortener-dev-app2:3000'
          - 'url-shortener-dev-app3:3000'
    metrics_path: '/metrics'
    scrape_interval: 30s